# Generated by Django 4.0.5 on 2022-06-25 00:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('voucher', models.CharField(max_length=14)),
                ('credits', models.IntegerField(default=0, verbose_name='Credits')),
                ('type', models.CharField(choices=[('1', 'ADD'), ('2', 'CREDIT'), ('3', 'DEBIT'), ('4', 'INVALID')], default='1', max_length=1, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_credicts', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('expriration_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'credit',
                'verbose_name_plural': 'Credits',
                'db_table': 'mimo_activitys',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('text', models.TextField()),
                ('unicode', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mimo_message',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(db_index=True, max_length=11)),
                ('reason', models.TextField(default='', max_length=100)),
                ('status', models.CharField(choices=[('1', 'ENABLE'), ('2', 'DISABLED')], max_length=8)),
                ('default', models.BooleanField(default=False, verbose_name='Pattern')),
            ],
            options={
                'db_table': 'mimo_senders',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=9)),
                ('messageId', models.CharField(max_length=25, verbose_name='Message ID')),
                ('status', models.CharField(choices=[('S', 'SENT'), ('P', 'PENDING'), ('D', 'DELIVERED')], default='P', max_length=1)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mimo_sms.message')),
            ],
            options={
                'db_table': 'mimo_recipients',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mimo_sms.sender'),
        ),
    ]
